### ISSUE TITLE
Priemgetallen

### ISSUE THREAD

**Issue by svanimpe** [Web-II/01solJavascriptBasis#2]
Moet dat hier niet `dividend <= Math.sqrt(number)` zijn, ipv `dividend <= number / 2`?

https://github.com/Web-II/01solJavascriptBasis/blob/bff85188d9ade0bc7e4b11f1c2a384e1615eaf25/oefening6/scripts/primeNumbers.js#L8

**Comment by ghost** [comment]
Correct, kijk naar #3
